.PHONY: clean All

All:
	@echo "----------Building project:[ PEC8 - Debug ]----------"
	@cd "PEC8" && "$(MAKE)" -f  "PEC8.mk"
clean:
	@echo "----------Cleaning project:[ PEC8 - Debug ]----------"
	@cd "PEC8" && "$(MAKE)" -f  "PEC8.mk" clean
